version: '3.3'
services:
  backend: &backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/app:rw,cached
      - gem_modules:/usr/local/bundle
    links:
      - db
    env_file:
      - .env
    command: 'sleep infinity'
    ports:
      - 3000:3000

  db:
    image: postgres:9.5
    env_file: docker/postgres/dev.env
    ports:
      - 5432:5432
  redis:
    image: redis:4.0
    ports:
      - 6379:6379

volumes:
  gem_modules:
